name: 'v2ray-ws-tls-cloudflared-tunnel'
inputs:
  id:
    required: true
  path:
    required: true
  token:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.id }}
    - ${{ inputs.path }}
    - ${{ inputs.token }}
